### ISSUE TITLE
`web.dom-exception.stack` module throws an error with Node < 17

### ISSUE THREAD

**Issue by ingmarh** [zloirock/core-js#1067]
First of all, thanks for creating and maintaining `core-js`!

I noticed an error when the `web.dom-exception.stack` module gets imported with Node < 17:

```
/project/node_modules/core-js/modules/web.dom-exception.stack.js:31
var DOMExceptionPrototype = $DOMException.prototype = NativeDOMException.prototype;
                                                                         ^

TypeError: Cannot read properties of undefined (reading 'prototype')
    at Object.<anonymous> (/project/node_modules/core-js/modules/web.dom-exception.stack.js:31:74)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/project/packages/fusion-frontend/build/utils/jwtDecode.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/project/packages/fusion-frontend/build/web/store/actions/customer.js:22:41)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/project/packages/fusion-frontend/build/web/store/actions/index.js:33:17)
```

```bash
$ node --version
v16.14.2
```

(Using `core-js` version 3.21.1, but the error reproduces also with previous versions.)

## Additional information

I’m using `core-js` via `@babel/preset-env` with the following configuration:

```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "corejs": "3.21",
        "bugfixes": true,
        "shippedProposals": true
      }
    ]
  ]
}
```

I tried to find out if it is an issue with `core-js` or with a Babel dependency. It looked to me that the issue is in `core-js`.
It works when using Node 17 (which adds the global `DOMException`), but not with the current LTS version Node 16.

We are now using `"corejs": "3.19"` in the Babel preset-env config, which works for us since we currently don’t actually need the [`core-js` v3.20+ modules](https://github.com/zloirock/core-js/blob/44ae6f1a3402090d4f37e3b58d60328cb10aa267/packages/core-js-compat/src/modules-by-versions.mjs#L114-L162) in our app.

**Comment by zloirock** [comment]
This error could happen if for any reason `web.dom-exception.constructor` is missed before `web.dom-exception.stack` in your code.

**Comment by ingmarh** [comment]
> This error could happen if for any reason `web.dom-exception.constructor` is missed before `web.dom-exception.stack` in your code - but `preset-env` should import it for Node < 17 targets. Maybe you use Node 17 target?

This explains it.

`web.dom-exception.constructor` was indeed missing before `web.dom-exception.stack`. `@babel/preset-env` only imported `web.dom-exception.stack` because of the target configuration:

We are using `browserslists` and have it globally configured to `last 2 major versions and supports es6-module` in a universal app. Many files are used on the server and client, but the file were the error occured actually is server-only.

So the issue is in our app and can be solved by using a different `@babel/preset-env` config for back-end only code. I tried it, explicitly targeting `current node` for the directory of the file and can confirm that `web.dom-exception.constructor` is then loaded before and it works, as expected.

Thanks for your fast, helpful comments!
