### ISSUE TITLE
TypeError: StackFrame is not a constructor

### ISSUE THREAD

**Issue by DWang92** [zloirock/core-js#1088]
Got this error when trying to build a project with core-js v3.22.8

```
ERROR  TypeError: StackFrame is not a constructor
TypeError: StackFrame is not a constructor
    at Object.<anonymous> (/home/runner/work/ConsoleFrontend/ConsoleFrontend/node_modules/error-stack-parser/error-stack-parser.js:76:24)
    at Array.map (<anonymous>)
    at Object.ErrorStackParser$$parseV8OrIE [as parseV8OrIE] (/home/runner/work/ConsoleFrontend/ConsoleFrontend/node_modules/error-stack-parser/error-stack-parser.js:56:29)
    at Object.ErrorStackParser$$parse [as parse] (/home/runner/work/ConsoleFrontend/ConsoleFrontend/node_modules/error-stack-parser/error-stack-parser.js:31:29)
    at getOriginalErrorStack (/home/runner/work/ConsoleFrontend/ConsoleFrontend/node_modules/@soda/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:31:29)
    at extractError (/home/runner/work/ConsoleFrontend/ConsoleFrontend/node_modules/@soda/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:22:20)
    at Array.map (<anonymous>)
    at processErrors (/home/runner/work/ConsoleFrontend/ConsoleFrontend/node_modules/@soda/friendly-errors-webpack-plugin/src/core/transformErrors.js:31:17)
    at FriendlyErrorsWebpackPlugin.displayErrors (/home/runner/work/ConsoleFrontend/ConsoleFrontend/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:97:29)
    at doneFn (/home/runner/work/ConsoleFrontend/ConsoleFrontend/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:57:[14](https://github.com/Stompy-io/ConsoleFrontend/runs/6749645966?check_suite_focus=true#step:6:15))
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/runner/work/ConsoleFrontend/ConsoleFrontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (/home/runner/work/ConsoleFrontend/ConsoleFrontend/node_modules/tapable/lib/Hook.js:[15](https://github.com/Stompy-io/ConsoleFrontend/runs/6749645966?check_suite_focus=true#step:6:16)4:[20](https://github.com/Stompy-io/ConsoleFrontend/runs/6749645966?check_suite_focus=true#step:6:21))
    at /home/runner/work/ConsoleFrontend/ConsoleFrontend/node_modules/webpack/lib/Compiler.js:304:[22](https://github.com/Stompy-io/ConsoleFrontend/runs/6749645966?check_suite_focus=true#step:6:23)
    at Compiler.emitRecords (/home/runner/work/ConsoleFrontend/ConsoleFrontend/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/runner/work/ConsoleFrontend/ConsoleFrontend/node_modules/webpack/lib/Compiler.js:298:10
    at /home/runner/work/ConsoleFrontend/ConsoleFrontend/node_modules/webpack/lib/Compiler.js:485:14
npm ERR! code ELIFECYCLE
```

**Comment by zloirock** [comment]
It's not a `core-js` issue, the problem is in your build process in `webpack` or one of your plugins. I can't help here.
