### ISSUE TITLE
The webpack-cli dependency commander required for the build is old.

### ISSUE THREAD

**Issue by wafflook** [zloirock/core-js#1093]
Hi, core-js is great project !!! :)
An error occurred while running node_modules/webpack-cli@4.10.0.

# 1.Step
``` bash
npm install
npm run init
npm run bundle
```
# 2.Step
``` bash
C:\Users\wafflook\Desktop\core-js-master>npm run bundle

> bundle
> run-p bundle-package bundle-helpers bundle-tests-global bundle-tests-pure


> bundle-package
> zx scripts/bundle.mjs


> bundle-tests-global
> webpack --entry ./tests/tests/index.js --output-filename tests.js


> bundle-helpers
> webpack --entry ./tests/helpers/qunit-helpers.js --output-filename qunit-helpers.js


> bundle-tests-pure
> webpack --entry ./tests/pure/index.js --output-filename pure.js

C:\Users\wafflook\Desktop\core-js-master\node_modules\webpack-cli\lib\webpack-cli.js:16
        this.program.name("webpack");
                     ^

TypeError: Cannot read properties of undefined (reading 'name')
    at new WebpackCLI (C:\Users\wafflook\Desktop\core-js-master\node_modules\webpack-cli\lib\webpack-cli.js:16:22)
    at runCLI (C:\Users\wafflook\Desktop\core-js-master\node_modules\webpack-cli\lib\bootstrap.js:7:17)
    at Object.<anonymous> (C:\Users\wafflook\Desktop\core-js-master\node_modules\webpack-cli\bin\cli.js:17:1)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (C:\Program Files (x86)\Nodist\bin\node_modules\webpack-cli\node_modules\import-local\index.js:16:66)

Node.js v18.4.0
C:\Users\wafflook\Desktop\core-js-master\node_modules\webpack-cli\lib\webpack-cli.js:16
        this.program.name("webpack");
```
# 3.Step "Failed Destructuring assignment"
``` javascript
const { program, Option } = require("commander");
const WEBPACK_PACKAGE = process.env.WEBPACK_PACKAGE || "webpack";
const WEBPACK_DEV_SERVER_PACKAGE = process.env.WEBPACK_DEV_SERVER_PACKAGE || "webpack-dev-server";
class WebpackCLI {
    constructor() {
        this.colors = this.createColors();
        this.logger = this.getLogger();
        // Initialize program
        this.program = program;
        this.program.name("webpack");
        this.program.configureOutput({
            writeErr: this.logger.error,
            outputError: (str, write) => write(`Error: ${this.capitalizeFirstLetter(str.replace(/^error:/, "").trim())}`),
        });
    }
```

# Webpack required ^7.0.0
``` json
{
  "name": "webpack-cli",
  "dependencies": {
    "commander": "^7.0.0"
  }
}
```

# Installed commander@7.2.0
``` json
{
  "name": "commander",
  "version": "7.2.0"
}
```

# Updated commander@9.3.0
``` bash
cd node_modules/webpack-cli
npm install commander@9.3.0
npm run bundle
```

# Fixed
``` bash
> bundle
> run-p bundle-package bundle-helpers bundle-tests-global bundle-tests-pure


> bundle-package
> zx scripts/bundle.mjs


> bundle-helpers
> webpack --entry ./tests/helpers/qunit-helpers.js --output-filename qunit-helpers.js


> bundle-tests-global
> webpack --entry ./tests/tests/index.js --output-filename tests.js


> bundle-tests-pure
> webpack --entry ./tests/pure/index.js --output-filename pure.js

bundling: packages/core-js-bundle/index.js, size: 672.73KB
webpack compiled successfully
minification: packages/core-js-bundle/minified.js, size: 205.89KB
webpack compiled successfully
webpack compiled successfully
```

**Comment by wafflook** [comment]
Looks like the webpack and webpack-cli I'm using old version
sorry

**Comment by zloirock** [comment]
Yep, it seems the problem is on your side. I have the same NPM version, but I can't reproduce it.
