### ISSUE TITLE
Starting with 3.25.4: "wmhas is not a function"

### ISSUE THREAD

**Issue by DamienCassou** [zloirock/core-js#1133]
Starting with core-js 3.25.4, I'm starting to see errors in my CI pipeline when running [Storybook](storybook.js.org/):

```
[TEST]     TypeError: wmhas is not a function
[TEST] 
[TEST]       at has (node_modules/core-js/internals/internal-state.js:44:12)
[TEST]       at enforce (node_modules/core-js/internals/internal-state.js:17:10)
[TEST]       at Object.<anonymous>.module.exports (node_modules/core-js/internals/make-built-in.js:39:15)
[TEST]       at Object.<anonymous> (node_modules/core-js/internals/make-built-in.js:47:31)
[TEST]       at Object.<anonymous> (node_modules/core-js/internals/define-built-in.js:3:19)
```

Workaround: Stick with 3.25.3 and things work perfectly fine.

**Comment by zloirock** [comment]
In what environment is your CI launched?

**Comment by zloirock** [comment]
The only way why it could happen between 3.25.3 and 3.25.4 what I see is that in your environment `WeakMap.prototype.has instanceof Function` is `false`.

**Comment by DamienCassou** [comment]
```
[TEST] ---------------------------------
[TEST] WeakMap.prototype.has instanceof Function: true
[TEST] ---------------------------------
```

**Comment by zloirock** [comment]
Really, replacement of `fn` to `fn instanceof Function` [here](https://github.com/zloirock/core-js/blob/fd7812ac33079af134fc3269d236195b7b1bd9e3/packages/core-js/internals/function-uncurry-this.js#L13) somehow breaks you CI. In this case, I'm confusing why `WeakMap.prototype.has instanceof Function` in your test is `true`.

**Comment by jtoar** [comment]
We're seeing this in our CI as well: https://github.com/redwoodjs/redwood/actions/runs/3173018932/jobs/5170008129#step:11:123. But I can reproduce it locally fairly easily by creating a redwood app and trying to test the api side:

```
yarn create redwood-app my-rw-app
cd my-rw-app
yarn rw test --no-watch

Determining test suites to run...
Running Prisma CLI...
$ yarn prisma db push --force-reset --accept-data-loss --schema /Users/dom/prjcts/cores-iss/api/db/schema.prisma

Environment variables loaded from .env
Prisma schema loaded from api/db/schema.prisma
Datasource "db": SQLite database "test.db" at "file:/Users/dom/prjcts/cores-iss/node_modules/@redwoodjs/testing/config/jest/api/.redwood/test.db"

SQLite database test.db created at file:/Users/dom/prjcts/cores-iss/node_modules/@redwoodjs/testing/config/jest/api/.redwood/test.db

The SQLite database "test.db" from "file:/Users/dom/prjcts/cores-iss/node_modules/@redwoodjs/testing/config/jest/api/.redwood/test.db" was successfully reset.

🚀  Your database is now in sync with your Prisma schema. Done in 2ms

✔ Generated Prisma Client (4.3.1 | library) to ./node_modules/@prisma/client in 52ms

 PASS   api  api/src/directives/requireAuth/requireAuth.test.ts
 FAIL   api  api/src/directives/skipAuth/skipAuth.test.ts
  ● Test suite failed to run

    TypeError: wmhas is not a function

    > 1 | import { getDirectiveName } from '@redwoodjs/testing/api'
        | ^
      2 |
      3 | import skipAuth from './skipAuth'
      4 |

      at set (node_modules/core-js-pure/internals/internal-state.js:35:9)
      at node_modules/core-js-pure/internals/collection.js:37:7
      at new Map (node_modules/core-js-pure/modules/es.map.constructor.js:8:34)
      at Object.<anonymous>.module.exports (node_modules/core-js-pure/internals/iterator-define.js:53:70)
      at Object.setStrong (node_modules/core-js-pure/internals/collection-strong.js:175:5)
      at Object.<anonymous>.module.exports (node_modules/core-js-pure/internals/collection.js:73:24)
      at Object.<anonymous> (node_modules/core-js-pure/modules/es.map.constructor.js:7:1)
      at Object.<anonymous> (node_modules/core-js-pure/modules/es.map.js:2:1)
      at Object.<anonymous> (node_modules/core-js-pure/es/map/index.js:2:1)
      at Object.<anonymous> (node_modules/core-js-pure/stable/map/index.js:1:55)
      at Object.<anonymous> (node_modules/core-js-pure/actual/map/index.js:1:55)
      at Object.<anonymous> (node_modules/core-js-pure/full/map/index.js:1:55)
      at Object.<anonymous> (node_modules/core-js-pure/features/map/index.js:1:59)
      at Object.<anonymous> (node_modules/@babel/runtime-corejs3/core-js/map.js:1:59)
      at Object.<anonymous> (node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:27:36)
      at Object.<anonymous> (node_modules/@redwoodjs/graphql-server/dist/index.js:172:16)
      at Object.<anonymous> (node_modules/@redwoodjs/testing/dist/api/directive.js:18:22)
      at Object.<anonymous> (node_modules/@redwoodjs/testing/dist/api/index.js:43:18)
      at Object.<anonymous> (node_modules/@redwoodjs/testing/api/index.js:2:18)
      at Object.<anonymous> (api/src/directives/skipAuth/skipAuth.test.ts:1:1)
```

I'll continue debugging, but let me know if I can do something specific that would help!

**Comment by zloirock** [comment]
In the `internal-state` module we unbind `new WeakMap().has`:
https://github.com/zloirock/core-js/blob/fd7812ac33079af134fc3269d236195b7b1bd9e3/packages/core-js/internals/internal-state.js#L30-L32
In 3.25.4, for working around a Nashorn bug, in `function-uncurry-this`, we replace `fn` with `fn instanceof Function` - and after that, in your cases, the result of this expression is falsy:
https://github.com/zloirock/core-js/blob/fd7812ac33079af134fc3269d236195b7b1bd9e3/packages/core-js/internals/function-uncurry-this.js#L13
Why? I still have no idea. Need to dig.

**Comment by zloirock** [comment]
Avoiding `uncurryThis`,
https://github.com/zloirock/core-js/blob/fd7812ac33079af134fc3269d236195b7b1bd9e3/packages/core-js/internals/internal-state.js#L29-L46
, replacement to
```js
if (NATIVE_WEAK_MAP || shared.state) {
  var store = shared.state || (shared.state = new WeakMap());
  store.get = store.get;
  store.has = store.has;
  store.set = store.set;
  set = function (it, metadata) {
    if (store.has(it)) throw TypeError(OBJECT_ALREADY_INITIALIZED);
    metadata.facade = it;
    store.set(it, metadata);
    return metadata;
  };
  get = function (it) {
    return store.get(it) || {};
  };
  has = function (it) {
    return store.has(it);
  };
} else {
```
fixes `wmhas` problem - but without understanding what happens it could cause problems in other cases where `uncurryThis` is used, so anyway need to dig out what happens.

**Comment by zloirock** [comment]
I still can't reproduce this issue in any other env, only in this Storybook CI.

**Comment by zloirock** [comment]
It seems that in your cases used weak maps from iframes. They have another realms and `Function` and `iframe.WeakMap.prototype.has instanceof Function` will be `false`.

**Comment by jtoar** [comment]
This outside my wheelhouse, but that sounds likely since we're seeing this in a Jest environment, and we recently upgraded from Jest 27 to Jest 29, which included a jsdom major version bump as well (from 19 to 20). Looking through release notes and diffs for clues.

**Comment by zloirock** [comment]
Fixed in [`3.25.5`](https://github.com/zloirock/core-js/releases/tag/v3.25.5).

**Comment by DamienCassou** [comment]
Thank you very much

**Comment by Tobbe** [comment]
Fix confirmed for Redwood projects! Thanks a lot for the quick turnaround on this @zloirock 

![image](https://user-images.githubusercontent.com/30793/193654117-b32b3c04-2a5d-4e50-b765-757309e67ee6.png)

**Comment by ndelangen** [comment]
Thank you @zloirock ❤️
