### ISSUE TITLE
Issue getting "this" context

### ISSUE THREAD

**Issue by SorsOps** [zloirock/core-js#1231]
See the following repo to reproduce https://github.com/SorsOps/corejs-reproducible-this

I used core-js@3.30.0 for this instance

I've been investigating a weird inconsistency in figma plugins using core-js. When run in the developer vm, the following error would get thrown 

```
figma_app.min.js.br:formatted:1782 TypeError: Cannot read properties of undefined (reading 'process')
    at ./node_modules/core-js/internals/engine-v8-version.js (engine-v8-version.js:4:1)
    at __webpack_require__ (compat get default export:2:1)
    at ./node_modules/core-js/internals/symbol-constructor-detection.js (symbol-constructor-detection.js:12:1)
    at __webpack_require__ (compat get default export:2:1)
    at ./node_modules/core-js/internals/use-symbol-as-uid.js (use-symbol-as-uid.js:6:1)
    at __webpack_require__ (compat get default export:2:1)
    at ./node_modules/core-js/internals/is-symbol.js (is-symbol.js:13:1)
    at __webpack_require__ (compat get default export:2:1)
    at ./node_modules/core-js/internals/to-primitive.js (to-primitive.js:13:1)
    at __webpack_require__ (compat get default export:2:1)
```

I'm using the developer VM checkbox when developing a figma plugin to test other inconsistencies in another project,

The above error seems to be related to [this](https://github.com/zloirock/core-js/blob/280680b8f77094031e3908823c81a9be3e6d6817/packages/core-js/internals/global.js#L6) 

When console logging each of the properties that core-js is checking for, I see that all are undefined in the developer VM. The exception is to just use the `this` context itself. I'm assuming attempting to access the `this` context doesn't work for all other platforms, but is it possible to add `|| this ` for the check in case all the proceeding attempts to access the global context fail?

When using the non developer VM, the first option, `globalThis` resolves and everything works fine

![image](https://user-images.githubusercontent.com/80043879/229833481-5d840e2a-673c-442a-a7af-b01e1408b1e8.png)

![image](https://user-images.githubusercontent.com/80043879/229833788-55b60b8b-4f0c-4233-9431-0ad1ce209b77.png)

Additionally when changing the import to core-js to be `core-js/stable` (as opposed to `core-js/stable/symbol` I am using for the reproducible example) I also get the following error 

```
figma_app.min.js.br:formatted:1782 TypeError: 'atob' is read-only
    at <anonymous> (PLUGIN_1_SOURCE:2265)
    at <anonymous> (PLUGIN_1_SOURCE:2900)
    at ./node_modules/core-js/modules/web.atob.js (PLUGIN_1_SOURCE:17041)
    at __webpack_require__ (PLUGIN_1_SOURCE:20008)
    at ./node_modules/core-js/stable/index.js (PLUGIN_1_SOURCE:19965)
    at __webpack_require__ (PLUGIN_1_SOURCE:20008)
    at <anonymous> (PLUGIN_1_SOURCE:20076)
    at <anonymous> (PLUGIN_1_SOURCE:20081)
    at <anonymous> (PLUGIN_1_SOURCE:20083)
    at call (native)
    at <eval> (PLUGIN_1_SOURCE:20087)
``` 

This cascades for more operations (like `btoa`, etc) where core-js is attempting to override the values.

When using an earlier version of core-js@3.9.1 I did not get any of these errors, so this feels like a regression in behaviour. If its related to ensuring behaviour by overriding existing default lib functions like this, what would you suggest to return to the previous behaviour in the later versions of core-js

**Comment by zloirock** [comment]
Sorry for the delayed reply.

How can I reproduce it and what environment is used? I tried running the example from your repo, and it works fine in a browser.

The last line from `internals/global.js` should work properly and return a correct global this in any at least somehow correct JS engine, I didn't see any example where it can't work.

**Comment by zloirock** [comment]
Ok, I don't wanna dig Figma plugins infrastucture, but I belive that it's possible. I will add a fallback just to `this` for this case, but I'm not sure that some other cases will properly work in Figma plugins - it seems it's far from minimal required ES subset where `core-js` can properly work.

**Comment by zloirock** [comment]
About the second issue, you could take a look at https://github.com/zloirock/core-js#configurable-level-of-aggressiveness
