### ISSUE TITLE
3.32.0 : TypeError: Cannot assign to read only property 'structuredClone' of object '[object global]'

### ISSUE THREAD

**Issue by jean-humann** [zloirock/core-js#1281]
Hello `core-js` community ✋,

I'm using `core-js` in my jest test [here](https://github.com/jean-humann/docs-to-pdf/blob/master/jest.config.ts#L131)
The test were working fine till dependabot open this PR to update version to [3.32.0](https://github.com/jean-humann/docs-to-pdf/pull/157)
I have a new error in the jest test with 3.32:

```
TypeError: Cannot assign to read only property 'structuredClone' of object '[object global]'

      at Object.<anonymous>.module.exports (node_modules/core-js/internals/define-built-in.js:13:24)
      at Object.<anonymous>.module.exports (node_modules/core-js/internals/export.js:53:5)
      at Object.<anonymous> (node_modules/core-js/modules/web.structured-clone.js:6[12](https://github.com/jean-humann/docs-to-pdf/actions/runs/5808871705/job/15746546250?pr=157#step:5:13):1)
      at Object.<anonymous> (node_modules/core-js/full/index.js:450:1)
      at Object.<anonymous> (node_modules/core-js/index.js:2:18) 
```

Cf: https://github.com/jean-humann/docs-to-pdf/actions/runs/5808871705/job/15746546250?pr=157

Could you have a look please ?

**Comment by jean-humann** [comment]
> FYI, I believe this is node version specific - v18 works fine, but v19 + v20 don't. I presume they made `structuredClone` writable in v19 - @zloirock are there other polyfills that exist already that work around this problem? Did something change in the latest core-js release that could have impacted this?

You seem right, I deepdive in the gh actions history and I found this run where v18 works for the PR but not v19 and v20 : https://github.com/jean-humann/docs-to-pdf/actions/runs/5693855907/job/15510037805

**Comment by zloirock** [comment]
`core-js` is tested in those Node versions. They have an acceptable `structuredClone` descriptor:

![image](https://github.com/zloirock/core-js/assets/2213682/145a9b61-57ad-49e9-a33a-f46e4b61a4e5)

It looks like a conflict with something else that rewrites and breaks `structuredClone`.

If it's a problem reproducible in the mentioned PR, I'll take a look at this little later.

**Comment by joealden** [comment]
If it speeds debugging this up, I believe it's specific to the `jest-environment-node` - they are setting `structuredClone` [here](https://github.com/jestjs/jest/blob/c836fa8c7830e8457f427bca1bd4e6a4551051e2/packages/jest-environment-node/src/index.ts#L98-L103) for use in node tests. With that being said, I'm not sure if it's that assignment directly, or what happens in the their `installCommonGlobals` function that is called right below (or if it's somehow unrelated directly to either of those).

**Comment by sibelius** [comment]
is this a bug on core-js or jest ?

**Comment by zloirock** [comment]
@sibelius it's not a `core-js` or Node bug, something else overwrites `structuredClone` and makes it non-writable - Jest it or not - I still didn't check.

**Comment by zloirock** [comment]
As you could see above, this is not a `core-js` issue - someone else just breaks the environment, so I'm closing this.
