### ISSUE TITLE
conflict with promise-js

### ISSUE THREAD

**Issue by jseagull** [zloirock/core-js#161]
```shell
> require('promise-js')
{ [Function: Promise]
  all: [Function],
  cast: [Function],
  race: [Function],
  reject: [Function],
  resolve: [Function] }
> require('core-js')
TypeError: Cannot redefine property: Symbol(Symbol.iterator)
    at Object.defineProperty [as setDesc] (native)
    at module.exports.object.(anonymous function) (/home/seagull/huaban/muse/node_modules/core-js/modules/$.hide.js:4:12)
    at module.exports (/home/seagull/huaban/muse/node_modules/core-js/modules/$.iter-define.js:50:5)
    at Object.<anonymous> (/home/seagull/huaban/muse/node_modules/core-js/modules/es6.array.iterator.js:11:44)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by zloirock** [comment]
It's a bug in `promise-js`. `promise-js` forcibly replaces `Array#values` and `Array#@@iterator` (if those methods available and completely correct - too) and sets `configurable: false` for them (by the spec should be `true`). `Array#@@iterator.name` is `''`, but should be `'values'`, `core-js` trying o fix it, but methods are non-configurable.
