### ISSUE TITLE
DataView test fails in IE11

### ISSUE THREAD

**Issue by tregusti** [zloirock/core-js#202]
Thank you for this wonderful library! I wanted to track down another problem, but I stumbled on this failing test in [`master`](https://github.com/zloirock/core-js/tree/60a946b529d29e9a7a9773536c7fd716018de46c)

```
IE 11.0.0 (Windows 8.1 0.0.0) ES6 DataView FAILED
        throws without `new`
        Expected: "throws without `new`"
        Actual: undefined
           at Anonymous function (C:/code/core-js/tests/tests.js:9342:7)
           at runTest (C:/code/core-js/node_modules/qunitjs/qunit/qunit.js:843:4)
           at Test.prototype.run (C:/code/core-js/node_modules/qunitjs/qunit/qunit.js:828:4)
           at Anonymous function (C:/code/core-js/node_modules/qunitjs/qunit/qunit.js:970:6)
           at process (C:/code/core-js/node_modules/qunitjs/qunit/qunit.js:629:4)
           at begin (C:/code/core-js/node_modules/qunitjs/qunit/qunit.js:611:2)
```

**Comment by zloirock** [comment]
Hi. Thanks for the report. I know about it. This test was added when I wrote typed arrays / buffers polyfill. `DataView` constructor in some engines hadn't any other serious issues and I wasn't sure that was a reason for adding a wrapper for `DataView` constructor, so it's a test for a missing shim. I think to add it little later when I'll rework typed arrays / buffers polyfill.

**Comment by zloirock** [comment]
I think that already makes no sense to overwrite (wrap) `DataView` just because of this test.
