### ISSUE TITLE
Error: Cannot find module 'core-js/library/fn/json/stringify'

### ISSUE THREAD

**Issue by dkfiresky** [zloirock/core-js#215]
Just tried to install babel-register and got an issue with your module on Windows machine:

```sh
Error: Cannot find module 'core-js/library/fn/json/stringify'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/dev/projects/test/node_modules/babel-register/node_modules/babel-runtime/core-js/json/stringify.js:1:93)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

```

**Comment by zloirock** [comment]
You should update `core-js` and `babel-runtime` to actual versions.
