### ISSUE TITLE
Shim causing error with specific RegExp

### ISSUE THREAD

**Issue by wiredprairie** [zloirock/core-js#36]
I've been trying to get babel working with a node package that ultimate requires the package [xregexp](https://github.com/slevithan/XRegExp). I've narrowed the problem down so it's simple to reproduce.

If I create a simple script and install these two packages:

    > npm install babel
    > npm install xregexp

#### test.js - SUCCEEDS

    var xregexp = require('xregexp');

#### test.js - FAILS

    require("babel/register");
    var xregexp = require('xregexp');

I don't follow what the shim is trying to do, so I don't know how to attempt to fix it. 

Here is the stack trace for the error that happens:

    D:\TEMP\babel-issue1\node_modules\babel\node_modules\core-js\shim.js:1150
            ? pattern.source : pattern, flags);
                               ^
    SyntaxError: Invalid flags supplied to RegExp constructor 'gy'
        at RegExp (native)
        at new RegExp (D:\TEMP\babel-issue1\node_modules\babel\node_modules\core-js\shim.js:1150:28)
        at copy (D:\TEMP\babel-issue1\node_modules\xregexp\xregexp-all.js:154:29)
        at addToken.on (D:\TEMP\babel-issue1\node_modules\xregexp\xregexp-all.js:393:30)
        at D:\TEMP\babel-issue1\node_modules\xregexp\xregexp-all.js:1138:5
        at Object.<anonymous> (D:\TEMP\babel-issue1\node_modules\xregexp\xregexp-all.js:1267:2)
        at Module._compile (module.js:460:26)
        at Module._extensions..js (module.js:478:10)
        at Object.require.extensions.(anonymous function) [as .js] (D:\TEMP\babel-issue1\node_modules\babel\lib\babel\api\register\node.js:113:7)
        at Module.load (module.js:355:32)

**Comment by zloirock** [comment]
It's broken feature detection in xregexp. I already fixed it in core-js 0.6.0.
/cc @sebmck please, update dependencies.
/cc @slevithan [this line](https://github.com/slevithan/xregexp/blob/master/xregexp-all.js#L86) should throw  error in ES6 - `RegExp.prototype` hasn't [`[[OriginalFlags]]`](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-get-regexp.prototype.sticky).
