### ISSUE TITLE
Error: Cannot find module 'mypackage/node_modules/core-js/scripts/postinstall'

### ISSUE THREAD

**Issue by kopax** [zloirock/core-js#555]
Hi everyone,

I have a package that is just doing a gitlab-to-github push, it used to work for months (last edition of my script was in november 2018) but last attempt forced me to try to update things, without success:

```bash
+ npx @yeutech/gitlab-to-github github repository gitlab-to-github word-documentation organization=rollup-umd --exclude= --dev-source=master --dev-target=dev '--desc=Rollup-UMD documentation layout that aim to write a documentation/document with the styling of a word document' --homepage=https://rollup-umd.github.io/word-documentation
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/1355/lib/node_modules/@yeutech/gitlab-to-github/node_modules/core-js/scripts/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! core-js@2.6.6 postinstall: `node scripts/postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the core-js@2.6.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-20T19_12_44_700Z-debug.log
Install for @yeutech/gitlab-to-github@latest failed with code 1
```

I have tried to fix the version to v2.6.6 and for some reason it keep failing.

Did you people change something or is there something wrong I missed with another package?

**Comment by zloirock** [comment]
Dupe #551

**Comment by kopax** [comment]
@zloirock do you know you have the same name with a excellent [DJ from moscow](https://www.residentadvisor.net/dj/andreypushkarev)?

**Comment by zloirock** [comment]
@kopax didn't know it, interesting -)
