### ISSUE TITLE
Cannot find module 'core-js/modules/es.array.iterator'

### ISSUE THREAD

**Issue by acufelipe** [zloirock/core-js#562]
I have updated from 3.0.1 to 3.1.2 and got an exception with the following stack trace when uploading my functions to firebase functions server after compilation using babel:

```
Error: Cannot find module 'core-js/modules/es.array.iterator'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/model/index.js:3:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

my babelrc config just in case it helps:

```
{ 
  "plugins": [
    ["global-define", { "window": false, }]
  ],
  "presets": [
    ["@babel/env", { "targets": { "node": "8.15.0", }, "useBuiltIns": "usage", "corejs": "3" }],
  ],
  "ignore": [
    "**/*.client.js",
    "node_modules",
    "dist"
  ]
}
```

and babel command used to compile code with babel: 

`babel . -d dist --ignore .node_modules --ignore node_modules --ignore dist`

**Comment by zloirock** [comment]
This module [exists on npm](https://unpkg.com/core-js@3.1.2/modules/es.array.iterator), try to remove your `node_modules` and reinstall dependencies.

**Comment by acufelipe** [comment]
Hi @zloirock, thanks for your response. I already cleaned my node_modules and package-lock.json but still get the same error :S

**Comment by zloirock** [comment]
Anyway, the problem not in `core-js` package. Maybe with a cache.
