### ISSUE TITLE
TypeError: Function.prototype.toString requires that 'this' be a Function

### ISSUE THREAD

**Issue by capaj** [zloirock/core-js#649]
I get these when I run jest and I use inline snapshots.
They always throw like this: 
```
  ● Test suite failed to run

    TypeError: Function.prototype.toString requires that 'this' be a Function
        at toString (<anonymous>)

      at toString (node_modules/apollo-env/node_modules/core-js/internals/redefine.js:38:95)
      at _isNativeFunction (node_modules/prettier/index.js:2008:28)
      at _wrapNativeSuper (node_modules/prettier/index.js:2015:28)
      at node_modules/prettier/index.js:40648:5
      at createCommonjsModule (node_modules/prettier/index.js:184:35)
      at Object.<anonymous> (node_modules/prettier/index.js:40620:27)
```

when I try to save them.

I have a project where I don't have a `apollo-env` package and there jest runs fine, so the bug must be in here or in `apollo-env`.

**Comment by zloirock** [comment]
It's just a wrapper on `Function.prototype.toString` so you see it in your stack trace, without `core-js` you will have the same error. If you don't think so, please, add a reproducible example.

**Comment by capaj** [comment]
thanks for the response.
