### ISSUE TITLE
`console` is being deleted with `core-js/library`

### ISSUE THREAD

**Issue by sebmck** [zloirock/core-js#7]
```
> console
{ log: [Function],
  info: [Function],
  warn: [Function],
  error: [Function],
  dir: [Function],
  time: [Function],
  timeEnd: [Function],
  trace: [Function],
  assert: [Function],
  Console: [Function: Console] }
> require("core-js/library");
{ Object: {},
  Number: {},
  Math: {},
  String: {},
  Array: {},
  RegExp: {},
  _: {},
  Function: {},
  Date: {},
  locale: [Function],
  addLocale: [Function: addLocale] }
> console
ReferenceError: console is not defined
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.emit (events.js:98:17)
    at emitKey (readline.js:1095:12)
```

**Comment by sebmck** [comment]
```javascript
> require("core-js/library").Array.isArray
undefined
```

This should also work but it doesn't. I suspect it's because `Array.isArray` exists?

**Comment by zloirock** [comment]
@sebmck `Array.isArray` is a part of ECMAScript 5, not 6, "core-js/library" build not contains ES5 shim. About console - strange, this build should not touch it. Let me check.

**Comment by sebmck** [comment]
@zloirock Ah right, okay.

**Comment by zloirock** [comment]
@sebmck "core-js/library" not touch console after 0.3.3, which version are you using?

**Comment by sebmck** [comment]
@zloirock Looks like i was using 0.3.2. Sorry, thanks for your help!

**Comment by zloirock** [comment]
@sebmck it was 0.3.2-only bug after dirty fix in another builds.

Also, you can use `core.$for.getIterator(iterable)` instead of `iterable[Symbol.iterator]()`, if you wanna add "without pollution mode" to 6to5.
