### ISSUE TITLE
Observable unit tests are failing

### ISSUE THREAD

**Issue by Richienb** [zloirock/core-js#796]
Running:

```js
const Observable = require("core-js-pure/features/observable")
require("es-observable-tests").runTests(Observable)
```

Produces the following:

```
Starting tests...

Observable constructor

  Argument types
    The first argument cannot be a non-callable object OK
    The first argument cannot be a primative value OK
    The first argument cannot be a primative value OK
    The first argument cannot be a primative value OK
    The first argument cannot be a primative value OK
    The first argument can be a function OK
Promise { <pending> }
>
  Observable.prototype has a constructor property
    Property constructor exists on the object OK
    Property has a function value OK
    Function length is 1 OK
    Property is writable OK
    Property is non-enumerable OK
    Property is configurable OK
    Observable.prototype.constructor === Observable OK

  Subscriber function is not called by constructor
    The constructor does not call the subscriber function OK

Observable.prototype.subscribe

  Observable.prototype has a subscribe property
    Property subscribe exists on the object OK
    Property has a function value OK
    Function length is 1 OK
    Property is writable OK
    Property is non-enumerable OK
    Property is configurable OK

  Argument type
    Throws if observer is not an object FAIL
      Actual: undefined
      Expected: function TypeError() { [native code] }
    Throws if observer is not an object FAIL
      Actual: undefined
      Expected: function TypeError() { [native code] }
    Throws if observer is not an object FAIL
      Actual: undefined
      Expected: function TypeError() { [native code] }
    Throws if observer is not an object FAIL
      Actual: undefined
      Expected: function TypeError() { [native code] }
    Throws if observer is not an object FAIL
      Actual: undefined
      Expected: function TypeError() { [native code] }
    Any object may be an observer OK
    Any object may be an observer OK
    Any object may be an observer OK

  Function arguments
    First argument is next callback OK
    Second argument is error callback OK
    Third argument is complete callback FAIL
      Actual: complete:undefined
      Expected: complete:3
Error
    at Function arguments (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:972:32)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    Second and third arguments are optional FAIL
      Actual: undefined
      Expected: undefined
    Second and third arguments are optional OK

  Subscriber arguments
    Subscriber is called with an observer OK
    Subscriber is called with an observer OK
    Subscriber is called with an observer OK
    Subscriber is called with an observer OK
    Subscription observer's constructor property is Object OK

  Subscriber return types
    Undefined can be returned OK
    Null can be returned OK
    Functions can be returned OK
    Subscriptions can be returned OK
TypeError: [object Object] is not a function
    at module.exports (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\internals\a-function.js:3:11)  
    at new Subscription (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:71:9)
    at Observable.subscribe (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:159:12)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1041:86
    at Test.throws (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:455:9)
    at Subscriber return types (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1041:10)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    Non callable, non-subscription objects cannot be returned FAIL
      Actual: undefined
      Expected: function TypeError() { [native code] }
TypeError: 0 is not a function
    at module.exports (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\internals\a-function.js:3:11)  
    at new Subscription (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:71:9)
    at Observable.subscribe (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:159:12)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1043:83
    at Test.throws (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:455:9)
    at Subscriber return types (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1043:10)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    Non-functions cannot be returned FAIL
      Actual: undefined
      Expected: function TypeError() { [native code] }
TypeError: false is not a function
    at module.exports (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\internals\a-function.js:3:11)  
    at new Subscription (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:71:9)
    at Observable.subscribe (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:159:12)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1044:87
    at Test.throws (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:455:9)
    at Subscriber return types (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1044:10)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    Non-functions cannot be returned FAIL
      Actual: undefined
      Expected: function TypeError() { [native code] }

  Returns a subscription object
    Property unsubscribe exists on the object OK
    Property has a function value OK
    Function length is 0 OK
    Property is writable OK
    Property is non-enumerable OK
    Property is configurable OK
    Property closed exists on the object OK
    Property has a getter OK
    Function length is 0 OK
    Property does not have a setter OK
    Property is non-enumerable OK
    Property is configurable OK
    Subscribe returns an object OK
    Contructor property is Object OK
    closed property returns false before unsubscription OK
    Unsubscribe returns undefined OK
    Unsubscribe calls the cleanup function OK
    closed property is true after calling unsubscribe OK

  Cleanup function
    The cleanup function is called when unsubscribing OK
    The cleanup function is not called again when unsubscribe is called again OK
    The cleanup function is called when an error is sent to the sink OK
    The cleanup function is called when a complete is sent to the sink OK
    If a subscription is returned, then unsubscribe is called on cleanup OK
    Arguments are not forwarded to the unsubscribe function OK

  Exceptions thrown from the subscriber
Error
    at Exceptions thrown from the subscriber (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1155:21)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    Subscribe throws if the observer does not handle errors FAIL
      Actual: undefined
      Expected: Error
    Subscribe does not throw if the observer has an error method OK
    Subscribe sends an error to the observer OK

  Start method
    If the observer has a start method, it is called OK
    Start is called with the observer as the this value OK
    Start is called with the subscription as the first argument OK
    Start is called before the subscriber function is called OK
    If unsubscribe is called from start, the subscriber is not called OK

Observable.prototype[Symbol.observable]

  Observable.prototype has a Symbol.observable method
    Property @@observable exists on the object FAIL
      Actual: false
      Expected: true

  Return value

TypeError: Cannot read property 'value' of undefined
    at Return value (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1243:56)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


Observable.of

  Observable has an of property
    Property of exists on the object OK
    Property has a function value OK
    Function length is 0 OK
    Property is writable OK
    Property is non-enumerable OK
    Property is configurable OK

  Uses the this value if it's a function
    Observable.of will use the 'this' value if it is callable OK

  Uses 'Observable' if the 'this' value is not a function
    Observable.of will use 'Observable' if the this value is not callable OK

  Arguments are delivered to next
    All items are delivered and complete is called OK

Observable.from

  Observable has a from property
    Property from exists on the object OK
    Property has a function value OK
    Function length is 1 OK
    Property is writable OK
    Property is non-enumerable OK
    Property is configurable OK

  Allowed argument types
    Null is not allowed OK
    Undefined is not allowed OK
    Undefined is not allowed OK

  Uses the this value if it's a function
    Observable.from will use the 'this' value if it is callable OK

  Uses 'Observable' if the 'this' value is not a function
    Observable.from will use 'Observable' if the this value is not callable OK

  Symbol.observable method is accessed

TypeError: [object Object] is not iterable
    at module.exports (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\internals\get-iterator.js:7:11)    at Function.from (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:177:20)
    at Symbol.observable method is accessed (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1354:20)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


  Return value of Symbol.observable
    Throws if the return value of Symbol.observable is not an object OK
    Throws if the return value of Symbol.observable is not an object OK
    Throws if the return value of Symbol.observable is not an object OK
    Throws if the return value of Symbol.observable is not an object FAIL
      Actual: TypeError: [object Object] is not iterable
      Expected: undefined
    Throws if the return value of Symbol.observable is not an object FAIL
      Actual: TypeError: [object Object] is not iterable
      Expected: undefined

TypeError: [object Object] is not iterable
    at module.exports (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\internals\get-iterator.js:7:11)    at Function.from (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:177:20)
    at Return value of Symbol.observable (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1397:38)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


  Iterables: values are delivered to next
    All items are delivered and complete is called OK

  Non-convertibles throw
    If argument is not observable or iterable, subscribe throws OK

SubscriptionObserver.prototype.next

  SubscriptionObserver.prototype has an next method
    Property next exists on the object OK
    Property has a function value OK
    Function length is 1 OK
    Property is writable OK
    Property is non-enumerable OK
    Property is configurable OK

  Input value
    Input value is forwarded to the observer OK

  Return value
    Returns the value returned from the observer FAIL
      Actual: undefined
      Expected: [object Object]
    Returns undefined when closed OK

  Method lookup
    If property does not exist, then next returns undefined OK
    If property is undefined, then next returns undefined OK
    If property is null, then next returns undefined OK
TypeError: [object Object] is not a function
    at module.exports (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\internals\a-function.js:3:11)  
    at getMethod (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:24:35) 
    at SubscriptionObserver.next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:106:26)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1544:47
    at Test.throws (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:455:9)
    at Method lookup (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1544:10)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    If property is not a function, then an error is thrown FAIL
      Actual: undefined
      Expected: function TypeError() { [native code] }
    Method is not accessed until complete is called FAIL
      Actual: undefined
      Expected: 1
    Method is not accessed when subscription is closed OK
    Property is only accessed once during a lookup OK

  Cleanup functions
Error
    at Object.next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1587:57)
    at SubscriptionObserver.next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:107:36)
    at Cleanup functions (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1588:24)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    Cleanup function is called when next throws an error FAIL
      Actual: 0
      Expected: 1
Error
    at Cleanup functions (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1593:21)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    If both next and the cleanup function throw, then the error from the next method is thrown FAIL
      Actual: false
      Expected: true

SubscriptionObserver.prototype.error

  SubscriptionObserver.prototype has an error method
    Property error exists on the object OK
    Property has a function value OK
    Function length is 1 OK
    Property is writable OK
    Property is non-enumerable OK
    Property is configurable OK

  Input value
    Input value is forwarded to the observer OK
    Additional arguments are not forwarded OK

  Return value
    Returns the value returned from the observer FAIL
      Actual: undefined
      Expected: [object Object]
    Throws the input when closed FAIL
      Actual: undefined
      Expected: [object Object]

  Method lookup
Error
    at Method lookup (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1671:21)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    If property does not exist, then error throws the input FAIL
      Actual: undefined
      Expected: Error
Error
    at Method lookup (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1671:21)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    If property is undefined, then error throws the input FAIL
      Actual: undefined
      Expected: Error
Error
    at Method lookup (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1671:21)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    If property is null, then error throws the input FAIL
      Actual: undefined
      Expected: Error
TypeError: [object Object] is not a function
    at module.exports (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\internals\a-function.js:3:11)  
    at getMethod (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:24:35) 
    at SubscriptionObserver.error (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:120:27)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1688:47
    at Test.throws (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:455:9)
    at Method lookup (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1688:10)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    If property is not a function, then an error is thrown FAIL
      Actual: undefined
      Expected: function TypeError() { [native code] }
    Method is not accessed until error is called FAIL
      Actual: undefined
      Expected: 1
    Method is not accessed when subscription is closed OK
    Property is only accessed once during a lookup OK
    When method lookup occurs, subscription is closed OK

  Cleanup functions
undefined
    Cleanup function is called when observer does not have an error method OK
    Cleanup function is called when observer has an error method OK
Error
    at Object.get error [as error] (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1758:52)
    at SubscriptionObserver.error (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:120:46)
    at Cleanup functions (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1759:24)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    Cleanup function is called when method lookup throws OK
Error
    at Object.error (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1765:58)
    at SubscriptionObserver.error (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:121:38)
    at Cleanup functions (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1766:24)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    Cleanup function is called when method throws OK
Error
    at Cleanup functions (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1771:21)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1775:40
    at cleanupSubscription (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:32:7)
    at SubscriptionObserver.error (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:125:9)
    at Cleanup functions (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1778:24)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    If both error and the cleanup function throw, then the error from the error method is thrown FAIL
      Actual: false
      Expected: true

SubscriptionObserver.prototype.complete

  SubscriptionObserver.prototype has a complete method
    Property complete exists on the object OK
    Property has a function value OK
    Function length is 1 FAIL
      Actual: 0
      Expected: 1
    Property is writable OK
    Property is non-enumerable OK
    Property is configurable OK

  Input value
    Input value is forwarded to the observer FAIL
      Actual: undefined
      Expected: [object Object]
    Additional arguments are not forwarded OK

  Return value
    Returns the value returned from the observer FAIL
      Actual: undefined
      Expected: [object Object]
    Returns undefined when closed OK

  Method lookup
    If property does not exist, then complete returns undefined OK
    If property is undefined, then complete returns undefined OK
    If property is null, then complete returns undefined OK
TypeError: [object Object] is not a function
    at module.exports (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\internals\a-function.js:3:11)  
    at getMethod (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:24:35) 
    at SubscriptionObserver.complete (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:135:30)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1865:47
    at Test.throws (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:455:9)
    at Method lookup (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1865:10)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    If property is not a function, then an error is thrown FAIL
      Actual: undefined
      Expected: function TypeError() { [native code] }
    Method is not accessed until complete is called FAIL
      Actual: undefined
      Expected: 1
    Method is not accessed when subscription is closed OK
    Property is only accessed once during a lookup OK
    When method lookup occurs, subscription is closed OK

  Cleanup functions
    Cleanup function is called when observer does not have a complete method OK
    Cleanup function is called when observer has a complete method OK
Error
    at Object.get complete [as complete] (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1934:55)
    at SubscriptionObserver.complete (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:135:49)
    at Cleanup functions (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1935:24)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    Cleanup function is called when method lookup throws OK
Error
    at Object.complete (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1941:61)
    at SubscriptionObserver.complete (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:136:44)
    at Cleanup functions (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1942:24)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    Cleanup function is called when method throws OK
Error
    at Cleanup functions (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1947:21)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1951:40
    at cleanupSubscription (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:32:7)
    at SubscriptionObserver.complete (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\core-js-pure\modules\esnext.observable.js:139:9)
    at Cleanup functions (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:1954:24)
    at C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:756:21
    at new Promise (<anonymous>)
    at TestRunner._exec (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:754:16)
    at next (C:\Users\richi\Documents\GitHub\es6-observable\node_modules\es-observable-tests\es-observable-tests.js:780:28)    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    If both complete and the cleanup function throw, then the error from the complete method is thrown FAIL
      Actual: false
      Expected: true

SubscriptionObserver.prototype.closed

  SubscriptionObserver.prototype has a closed getter
    Property closed exists on the object OK
    Property has a getter OK
    Function length is 0 OK
    Property does not have a setter OK
    Property is non-enumerable OK
    Property is configurable OK

  Returns false when the subscription is active
    Returns false when the subscription is active OK

  Returns true when the subscription is closed
    Returns true after complete is called OK
    Returns true after error is called OK
    Returns true after unsubscribe is called OK

Passed 146 tests and failed 33 tests, with 3 errors
```

**Comment by zloirock** [comment]
Sorry, I run all those tests on CI - and I don't see any fails here. How I can reproduce it?

**Comment by Richienb** [comment]
@zloirock See: https://runkit.com/richienb/5f98c17a1d8e58001a7f99da

**Comment by zloirock** [comment]
Do you run tests from `es-observable-tests` package? IIRC it's obsolete, does not follow the current version of the spec, and was updated 4 years ago. `core-js` follow the current version of the spec and use [the test case from the proposal repo](https://github.com/tc39/proposal-observable/tree/master/test) directly.
