### ISSUE TITLE
npm install fails. RangeError: Wrong length!

### ISSUE THREAD

**Issue by straczowski** [zloirock/core-js#824]
Hey together,

currently my `npm install` fails. I am developing an Angular Application. 

This is the Error Message

```
> opencollective postinstall

app/node_modules/core-js/modules/_typed-buffer.js:157
  if(numberLength != byteLength)throw RangeError(WRONG_LENGTH);
                                ^

RangeError: Wrong length!
    at validateArrayBufferArguments (/app/node_modules/core-js/modules/_typed-buffer.js:157:39)
    at new ArrayBuffer (/app/node_modules/core-js/modules/_typed-buffer.js:247:29)
    at zlib.js:334:28
    at NativeModule.compile (internal/bootstrap/loaders.js:285:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:220:8)
    at loadNativeModule (internal/modules/cjs/helpers.js:23:9)
    at Function.Module._load (internal/modules/cjs/loader.js:694:15)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/node_modules/node-fetch/index.js:12:12)
```

i am using macOS Catalina 10.15.4 

and  node = v12.14.1 

can someone help me please?

**Comment by cherifya** [comment]
Downgrading node to v10.14.2 fixes the issue for me.

**Comment by DanielVenturini** [comment]
The above advice helped me. I was on node v10.22 and I changed it to v10.12 and fixed this error.

**Comment by charliematters** [comment]
Node 10.14.2 worked for me too - which versions of core-js are safe for which versions of node? Is there a compatibility list somewhere?

**Comment by zloirock** [comment]
Could you add a reproducible example?

**Comment by netsensei** [comment]
Hi,

I'm seeing this issue with Universalviewer (https://github.com/UniversalViewer/universalviewer) and node v12.18.3

How to reproduce:

Have node v12.18.3 installed (e.g. through nvm) and then do this:

```bash
$ mkdir example && cd example
$ npm init
$ npm install --save universalviewer@3.1.1
```

Output:

```bash
npm WARN deprecated core-js@2.4.1: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated @types/localforage@0.0.34: This is a stub types definition for localforage (https://github.com/localForage/localForage). localforage provides its own type definitions, so you don't need @types/localforage installed!
npm WARN deprecated @types/jszip@3.4.1: This is a stub types definition. jszip provides its own type definitions, so you do not need this installed.

> universalviewer@3.1.1 postinstall /vagrant/example/node_modules/universalviewer
> opencollective postinstall

/vagrant/example/node_modules/core-js/modules/_typed-buffer.js:157
  if(numberLength != byteLength)throw RangeError(WRONG_LENGTH);
                                ^

RangeError: Wrong length!
    at validateArrayBufferArguments (/vagrant/example/node_modules/core-js/modules/_typed-buffer.js:157:39)
    at new ArrayBuffer (/vagrant/example/node_modules/core-js/modules/_typed-buffer.js:247:29)
    at zlib.js:344:28
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:277:7)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:219:10)
    at loadNativeModule (internal/modules/cjs/helpers.js:24:9)
    at Function.Module._load (internal/modules/cjs/loader.js:849:15)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/vagrant/example/node_modules/node-fetch/index.js:12:12)
```

**Comment by zloirock** [comment]
@netsensei 
> npm WARN deprecated core-js@2.4.1: core-js@<3 is no longer maintained

It was published 5 years ago, the spec and the `core-js` behavior were changed after that (IIRC ES2016 and `core-js@2.5`).
