### ISSUE TITLE
sb migrate doesn't work

### ISSUE THREAD

**Issue by henrycity** [zloirock/core-js#854]
**Describe the bug**
I tried to migrate from storiesOf to CSF and I had this issue. I also had the same issue when running `upgrade-hierarchy-separators`.

```
npx -p @storybook/cli@next sb migrate --parser=tsx storiesof-to-csf --glob="**/*.stories.tsx"
=> Applying storiesof-to-csf: 57 files
npx: installed 217 in 8.391s
Processing 57 files... 
Spawning 11 workers...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 3 files to free worker...
/Users/henrycity/.npm/_npx/72712/lib/node_modules/@storybook/cli/node_modules/core-js/internals/global.js:13
check((typeof globalThis === "undefined" ? "undefined" : (0, _typeof2.default)(globalThis)) == 'object' && globalThis) || check((typeof window === "undefined" ? "undefined" : (0, _typeof2.default)(window)) == 'object' && window) || check((typeof self === "undefined" ? "undefined" : (0, _typeof2.default)(self)) == 'object' && self) || check((typeof global === "undefined" ? "undefined" : (0, _typeof2.default)(global)) == 'object' && global) || // eslint-disable-next-line no-new-func
                                                                              ^

TypeError: (0 , _typeof2.default) is not a function
    at Object.<anonymous> (/Users/henrycity/.npm/_npx/72712/lib/node_modules/@storybook/cli/node_modules/core-js/internals/global.js:8:9)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Module._compile (/Users/henrycity/.npm/_npx/72734/lib/node_modules/jscodeshift/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Object.newLoader [as .js] (/Users/henrycity/.npm/_npx/72734/lib/node_modules/jscodeshift/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/tri.tran/.npm/_npx/72712/lib/node_modules/@storybook/cli/node_modules/core-js/internals/path.js:1:14)
/Users/henrycity/.npm/_npx/72712/lib/node_modules/@storybook/cli/node_modules/core-js/internals/global.js:13
check((typeof globalThis === "undefined" ? "undefined" : (0, _typeof2.default)(globalThis)) == 'object' && globalThis) || check((typeof window === "undefined" ? "undefined" : (0, _typeof2.default)(window)) == 'object' && window) || check((typeof self === "undefined" ? "undefined" : (0, _typeof2.default)(self)) == 'object' && self) || check((typeof global === "undefined" ? "undefined" : (0, _typeof2.default)(global)) == 'object' && global) || // eslint-disable-next-line no-new-func

All done. 
Results: 
0 errors
0 unmodified
0 skipped
0 ok
```

**System** 
```
System:
    OS: macOS 10.15.6
  Binaries:
    Node: 14.0.0
    npm: 6.14.4
  npmPackages:
    "@storybook/addon-a11y": "6.0.5",
    "@storybook/addon-actions": "6.0.5",
    "@storybook/addon-docs": "^6.0.6",
    "@storybook/addon-jest": "6.0.5",
    "@storybook/addon-knobs": "6.0.5",
    "@storybook/addon-links": "6.0.5",
    "@storybook/addon-viewport": "6.0.5",
    "@storybook/preset-create-react-app": "^3.1.4",
    "@storybook/react": "6.0.5",
    "@storybook/theming": "6.0.5",
    "core-js": "^3.6.5",
```

**Comment by henrycity** [comment]
Wrong repo
